version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@1.4.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      # https://circleci.com/gh/vzvu3k6k/lt-timer/5
      - run:
          name: Update bundler for workaround
          command: gem update bundler
      - ruby-orbs/bundle-install:
          restore_bundled_with: false
      - run:
          name: Compile
          command: bundle exec rake
      - persist_to_workspace:
          root: ./static
          paths:
            - ./*
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ./static
      - run:
          name: Configure Git
          command: |
            git config --global user.email "vzvu3k6k+cibuild@gmail.com"
            git config --global user.name "vzvu3k6k (CI build)"
      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages@2.0.1 --dist static --message "Updates [skip ci]"
workflows:
  version: 2
  test:
    jobs:
      - build
  publish:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - circleci
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - circleci
